app/views/parent.py
from os import stat
from werkzeug import utils
from app import *
from app.helperFunctions import *
from flask import (Blueprint, Flask, flash, g, redirect, render_template,
                   request, send_file, session, url_for)
from flask_mysqldb import MySQL
import hashlib
from werkzeug.utils import secure_filename
from datetime import datetime
from flask_mail import Mail, Message  
from datetime import date
import pandas as pd
import json

configData = getConfigsFromJson()
parent = Blueprint('parent', __name__, url_prefix='/parent') 
BASE_URL = configData["BASE_URL"]

#Login page
@parent.route('/', methods=['GET','POST'])
def home():
	user = getCurrentParentUser()
	if user:
		return redirect(url_for('parent.dashboard'))
	if request.method == 'POST':
		parentID = request.form['parent-login-userID']
		password = hashlib.md5(request.form['parent-login-password'].encode())
		result = query_db("select * from login_parent where userID=%s;",(parentID,))
		if result is not None:
			if result[0][1]==password.hexdigest():
				session['parentID']=parentID
				return redirect(url_for('parent.dashboard'))
			else:
				return render_template('parent/login.html',loginFlag=0)
		else:
			return render_template('parent/login.html',loginFlag=0)
	else:
		return render_template('parent/login.html',loginFlag=1)


# Dashboard
@parent.route('/dashboard', methods=['GET'])
def dashboard():
	user=getCurrentParentUser()
	if user:
		return redirect(url_for('parent.permissions'))
	else:
		return redirect(url_for('parent.home'))

@parent.route('/permissions', methods=['GET','POST'])
def permissions():
	user = getCurrentParentUser()
	cur = mysql.connection.cursor()
	if user:
		#getUserDetails
		userDetails = query_db("select userID, rollNumber, firstName, lastName from student_details where userID=%s;",(user[0][0],))
		
		#permissionsAdminControl
		permissionsAdminControlUrl = BASE_URL+"getPermissionsAdminControlls"
		permissionsAdminControlHeaders = {'Authorization': configData["AuthorizationToken"]}
		permissionsAdminControlResponse = requests.request("GET", permissionsAdminControlUrl, headers=permissionsAdminControlHeaders)
		permissionsAdminControls = json.loads(permissionsAdminControlResponse.text)
		permissionsAppActivated = permissionsAdminControls["activatePermissionsApp"]
		rulesInformation = permissionsAdminControls["informationToBeDisplayed"]
		inTime = permissionsAdminControls["inTime"]
		outTime = permissionsAdminControls["outTime"]

		#requestedPermissions
		requestedPermissionsUrl = BASE_URL+"getRequestedPermissions"
		requestedPermissionsparams = {'rollNumber': user[0][0]}
		requestedPermissionsheaders = {'Authorization':configData["AuthorizationToken"]}
		requestedPermissionsresponse = requests.request("GET", requestedPermissionsUrl, headers=requestedPermissionsheaders, params=requestedPermissionsparams)
		requestedPermissionsList = mapRequestedPermissionsToList(requestedPermissionsresponse.json())
		#activePermissions
		activePermissionsUrl = BASE_URL+"getActivePermissions"
		activePermissionsparams={'rollNumber': user[0][0]}
		activePermissionsheaders = {'Authorization':configData["AuthorizationToken"]}
		activePermissionsresponse = requests.request("GET", activePermissionsUrl, headers=activePermissionsheaders, params=activePermissionsparams)
		activePermissionsList = mapActivePermissionsToList(activePermissionsresponse.json())
		#expiredPermissions
		expiredPermissionsUrl = BASE_URL+"getExpiredPermissions"
		expiredPermissionsparams={'rollNumber': user[0][0]}
		expiredPermissionsheaders = {'Authorization':configData["AuthorizationToken"]}
		expiredPermissionsresponse = requests.request("GET", expiredPermissionsUrl, headers=expiredPermissionsheaders, params=expiredPermissionsparams)
		expiredPermissionsList = mapExpiredPermissionsToList(expiredPermissionsresponse.json())
		
		if request.method == 'GET':
			return render_template('/parent/permissions.html', user = userDetails, requestedPermissionsList = requestedPermissionsList, activePermissionsList = activePermissionsList, expiredPermissionsList = expiredPermissionsList, appActivation = permissionsAppActivated, invalidTime = 0, inTime = inTime, outTime = outTime, rulesInformation = rulesInformation)
		
		if request.method=='POST':
			#approve permission
			if request.form['submit'].split(':')[0]=='acceptPermission':
				permissionId = request.form['submit'].split(':')[1]
				url = BASE_URL+"acceptPermission"
				payload={"permissionId":permissionId}
				headers = {'Authorization': configData["AuthorizationToken"]}
				response = requests.request("POST", url, headers=headers, data=payload)
				return redirect(url_for("parent.permissions"))
				
			#reject permission
			elif request.form['submit'].split(':')[0]=='rejectPermission':
				permissionId = request.form['submit'].split(':')[1]
				url = BASE_URL+"rejectPermission"
				payload={"permissionId":permissionId}
				headers = {'Authorization': configData["AuthorizationToken"]}
				response = requests.request("POST", url, headers=headers, data=payload)
				return redirect(url_for("parent.permissions"))
	else:
		return redirect(url_for('parent.home'))
	cur.close()

@parent.route('/forgot-password', methods=['GET','POST'])
def forgotPassword():
	pass

@parent.route('/logout')
def logout():
    user = getCurrentParentUser()
    if user:
        session.pop('parentID', None)
        return redirect(url_for('parent.home'))
    else:
        return redirect(url_for('parent.home'))

app/templates/parent/forgotPassword.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8" />
  <link rel="apple-touch-icon" sizes="76x76" href="{{url_for('static', filename='img/apple-icon.png')}}">
  <link rel="icon" type="image/png" href="{{url_for('static', filename='img/favicon.png')}}">
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
  <title>
    Forgot Password Page
  </title>
  <meta content='width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0, shrink-to-fit=no' name='viewport' />
  <!--     Fonts and icons     -->
  <link href="https://fonts.googleapis.com/css?family=Montserrat:400,700,200" rel="stylesheet" />
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.1/css/all.css" integrity="sha384-fnmOCqbTlWIlj8LyTjo7mOUStjsKC4pOpQbqyi7RrhN7udi9RwhKkMHpvLbHG9Sr" crossorigin="anonymous">
  <!-- CSS Files -->
  <link href="{{url_for('static', filename='css/bootstrap.min.css')}}" rel="stylesheet" />
  <link href="{{url_for('static', filename='css/now-ui-kit.css')}}" rel="stylesheet" />
  <!-- CSS Just for demo purpose, don't include it in your project -->
  <link href="{{url_for('static', filename='demo/demo.css')}}" rel="stylesheet" />
</head>

<body class="login-page sidebar-collapse">
  <!-- Navbar -->
  <nav class="navbar navbar-expand-lg bg-primary fixed-top navbar-transparent " color-on-scroll="400">
    <div class="container">
      <div class="dropdown button-dropdown">
        <a href="#pablo" class="dropdown-toggle" id="navbarDropdown" data-toggle="dropdown">
          <span class="button-bar"></span>
          <span class="button-bar"></span>
          <span class="button-bar"></span>
        </a>
       
      </div>
      <div class="navbar-translate">
        <a class="navbar-brand" href="#"rel="tooltip"  data-placement="bottom" >
          Hostel Webkiosk
        </a>
        <button class="navbar-toggler navbar-toggler" type="button" data-toggle="collapse" data-target="#navigation" aria-controls="navigation-index" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-bar top-bar"></span>
          <span class="navbar-toggler-bar middle-bar"></span>
          <span class="navbar-toggler-bar bottom-bar"></span>
        </button>
      </div>
      <div class="collapse navbar-collapse justify-content-end" id="navigation" data-nav-image="../static/img/blurred-image-1.jpg">
      
        
        </ul>
      </div>
    </div>
  </nav>
  <!-- End Navbar -->
  <div class="page-header clear-filter" filter-color="orange">
    <div class="page-header-image" style="background-image:url('../img/login.jpeg')"></div>
    <div class="content">
      <div class="container">
        <div class="col-md-4 ml-auto mr-auto">
          {% if detailsCheck == 1 %}
          <div align="center" class="alert alert-danger" role="alert">
            Parent ID or email is incorrect!
          </div>
          {% endif %}
          {% if success == 1 %}
          <div align="center" class="alert alert-success" role="alert">
            New password sent to your mail!
          </div>
          {% endif %}
          <div class="card card-login card-plain">
            <form class="form" method="POST" action="{{url_for('parent.forgotPassword')}}" onsubmit='disableButton()'>
              <div class="card-header text-center">
                <div class="logo-container">
                  <img src="img/now-logo.png" alt="">
                </div>
              </div>
              <div class="card-body">
                <div class="input-group no-border input-lg">
                  <div class="input-group-prepend">
                    <span class="input-group-text">
                      <i class="now-ui-icons users_circle-08"></i>
                    </span>
                  </div>
                  <input name="parent-id" type="text" class="form-control" placeholder="Parent ID">
                </div>
                <div class="input-group no-border input-lg">
                  <div class="input-group-prepend">
                    <span class="input-group-text">
                      <i class="fas fa-envelope-open"></i>
                    </span>
                  </div>
                  <input name="parent-phone" type="text" placeholder="Phone Number" class="form-control"/>
                </div>
                <div class="card-footer text-center">
                  <input type="submit" id="forgotSubmit" class="btn btn-primary btn-round btn-lg btn-block" value="Request Password">
                  <div class="pull-right">
                    <h6>
                    <a href="{{url_for('parent.home')}}" class="link">Back to Login</a>
                  </h6>
                  </div>
                </div>
              </div>
            </form>
            </div>
            
          </div>
        </div>
      </div>
    </div>
   
  </div>
  <!--   Core JS Files   -->
  <!--   Core JS Files   -->
  <script src="{{url_for('static', filename='dashboard/js/core/jquery.min.js')}}"></script>
  <script src="{{url_for('static', filename='dashboard/js/core/popper.min.js')}}"></script>
  <script src="{{url_for('static', filename='dashboard/js/core/bootstrap.min.js')}}"></script>
  <script src="{{url_for('static', filename='dashboard/js/plugins/perfect-scrollbar.jquery.min.js')}}"></script>
  <!--  Google Maps Plugin    -->
  <script src="https://maps.googleapis.com/maps/api/js?key=YOUR_KEY_HERE"></script>
  <!-- Chart JS -->
  <script src="{{url_for('static', filename='dashboard/js/plugins/chartjs.min.js')}}"></script>
  <!--  Notifications Plugin    -->
  <script src="{{url_for('static', filename='dashboard/js/plugins/bootstrap-notify.js')}}"></script>
  <!-- Control Center for Now Ui Dashboard: parallax effects, scripts for the example pages etc -->
  <script src="{{url_for('static', filename='dashboard/js/now-ui-dashboard.min.js')}}" type="text/javascript"></script><!-- Now Ui Dashboard DEMO methods, don't include it in your project! -->
  <script src="{{url_for('static', filename='dashboard/demo/demo.js')}}"></script>
  <script>
    function disableButton() {
        var btn = document.getElementById('forgotSubmit');
        btn.disabled = true;
        btn.innerText = 'Sending Mail...'
    }
</script>
</body>

</html>

app/templates/parent/login.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8" />
  <link rel="apple-touch-icon" sizes="76x76" href="{{url_for('static', filename='img/apple-icon.png')}}">
  <link rel="icon" type="image/png" href="{{url_for('static', filename='img/favicon.png')}}">
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
  <title>
    Login-Page
  </title>
  <meta content='width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0, shrink-to-fit=no' name='viewport' />
  <!--     Fonts and icons     -->
  <link href="https://fonts.googleapis.com/css?family=Montserrat:400,700,200" rel="stylesheet" />
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.1/css/all.css" integrity="sha384-fnmOCqbTlWIlj8LyTjo7mOUStjsKC4pOpQbqyi7RrhN7udi9RwhKkMHpvLbHG9Sr" crossorigin="anonymous">
  <!-- CSS Files -->
  <link href="{{url_for('static', filename='css/bootstrap.min.css')}}" rel="stylesheet" />
  <link href="{{url_for('static', filename='css/now-ui-kit.css')}}" rel="stylesheet" />
  <!-- CSS Just for demo purpose, don't include it in your project -->
  <link href="{{url_for('static', filename='demo/demo.css')}}" rel="stylesheet" />
</head>

<body class="login-page sidebar-collapse">
  <!-- Navbar -->
  <nav class="navbar navbar-expand-lg bg-primary fixed-top navbar-transparent " color-on-scroll="400">
    <div class="container">
      <div class="dropdown button-dropdown">
        <a href="#pablo" class="dropdown-toggle" id="navbarDropdown" data-toggle="dropdown">
          <span class="button-bar"></span>
          <span class="button-bar"></span>
          <span class="button-bar"></span>
        </a>
       
      </div>
      <div class="navbar-translate">
        <a class="navbar-brand" href="#"rel="tooltip"  data-placement="bottom" >
          Hostel Webkiosk (Parent Login)
        </a>
        <button class="navbar-toggler navbar-toggler" type="button" data-toggle="collapse" data-target="#navigation" aria-controls="navigation-index" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-bar top-bar"></span>
          <span class="navbar-toggler-bar middle-bar"></span>
          <span class="navbar-toggler-bar bottom-bar"></span>
        </button>
      </div>
      <div class="collapse navbar-collapse justify-content-end" id="navigation" data-nav-image="../img/blurred-image-1.jpg">
      
        
        </ul>
      </div>
    </div>
  </nav>
  <!-- End Navbar -->
  <div class="page-header clear-filter" filter-color="orange">
    <div class="page-header-image" style="background-image:url('../img/login.jpeg')"></div>
    <div class="content">
      <div class="container">
        <div class="col-md-4 ml-auto mr-auto">
          {% if loginFlag == 0 %}
          <div class="alert alert-danger" role="alert">
            The username or password is incorrect!
          </div>
          {% endif %}
          <div class="card card-login card-plain">
            <form class="form" method="POST" action="{{url_for('parent.home')}}">
              <div class="card-header text-center">
                <div class="logo-container">
                  <img src="img/now-logo.png" alt="">
                </div>
              </div>
              <div class="card-body">
                <div class="input-group no-border input-lg">
                  <div class="input-group-prepend">
                    <span class="input-group-text">
                      <i class="now-ui-icons users_circle-08"></i>
                    </span>
                  </div>
                  <input name="parent-login-userID" type="text" class="form-control" placeholder="Roll Number">
                </div>
                <div class="input-group no-border input-lg">
                  <div class="input-group-prepend">
                    <span class="input-group-text">
                      <i class="fas fa-key"></i>
                    </span>
                  </div>
                  <input name="parent-login-password" type="password" placeholder="Password" class="form-control" />
                </div>
              </div>
              <div class="card-footer text-center">
                <input type="submit" class="btn btn-primary btn-round btn-lg btn-block" value="Login">
                <div class="pull-right">
                  <h6>
                    <a href="{{url_for('parent.forgotPassword')}}" class="link">Forgot Password?</a>
                  </h6>
                </div>
            </form>
            
            </div>
            
          </div>
        </div>
      </div>
    </div>
   
  </div>
  <!--   Core JS Files   -->
  <script src="{{url_for('static', filename='dashboard/js/core/jquery.min.js')}}"></script>
  <script src="{{url_for('static', filename='dashboard/js/core/popper.min.js')}}"></script>
  <script src="{{url_for('static', filename='dashboard/js/core/bootstrap.min.js')}}"></script>
  <script src="{{url_for('static', filename='dashboard/js/plugins/perfect-scrollbar.jquery.min.js')}}"></script>
  <!--  Google Maps Plugin    -->
  <script src="https://maps.googleapis.com/maps/api/js?key=YOUR_KEY_HERE"></script>
  <!-- Chart JS -->
  <script src="{{url_for('static', filename='dashboard/js/plugins/chartjs.min.js')}}"></script>
  <!--  Notifications Plugin    -->
  <script src="{{url_for('static', filename='dashboard/js/plugins/bootstrap-notify.js')}}"></script>
  <!-- Control Center for Now Ui Dashboard: parallax effects, scripts for the example pages etc -->
  <script src="{{url_for('static', filename='dashboard/js/now-ui-dashboard.min.js')}}" type="text/javascript"></script><!-- Now Ui Dashboard DEMO methods, don't include it in your project! -->
  <script src="{{url_for('static', filename='dashboard/demo/demo.js')}}"></script>
</body>

</html>