app/views/guard.py
from os import stat
from werkzeug import utils
from app import *
from app.helperFunctions import *
from flask import (Blueprint, Flask, flash, g, redirect, render_template,
                   request, send_file, session, url_for)
from flask_mysqldb import MySQL
import hashlib
from werkzeug.utils import secure_filename
from datetime import datetime
from flask_mail import Mail, Message  
from datetime import date
import pandas as pd
import json
import pytz 
IST = pytz.timezone('Asia/Kolkata')

configData = getConfigsFromJson()
guard = Blueprint('guard', __name__, url_prefix='/guard') 
BASE_URL = configData["BASE_URL"]

#Login page
@guard.route('/', methods=['GET','POST'])
def home():
	user = getCurrentGuardUser()
	if user:
		return redirect(url_for('guard.permissions'))
	if request.method == 'POST':
		guardID = request.form['guard-login-userID']
		password = hashlib.md5(request.form['guard-login-password'].encode())
		result = query_db("select * from login_guard where userID=%s;",(guardID,))
		if result is not None:
			if result[0][1]==password.hexdigest():
				session['guardID']=guardID
				return redirect(url_for('guard.permissions'))
			else:
				return render_template('guard/login.html',loginFlag=0)
		else:
			return render_template('guard/login.html',loginFlag=0)
	else:
		return render_template('guard/login.html',loginFlag=1)


#permissions
@guard.route('/permissions', methods=['GET','POST'])
def permissions():
	user = getCurrentGuardUser()
	cur = mysql.connection.cursor()

	if user:

		#permissionsAdminControl
		permissionsAdminControlUrl = BASE_URL+"getPermissionsAdminControlls"
		permissionsAdminControlHeaders = {'Authorization': configData["AuthorizationToken"]}
		permissionsAdminControlResponse = requests.request("GET", permissionsAdminControlUrl, headers=permissionsAdminControlHeaders)
		permissionsAdminControls = json.loads(permissionsAdminControlResponse.text)
		permissionsAppActivated = permissionsAdminControls["activatePermissionsApp"]
		rulesInformation = permissionsAdminControls["informationToBeDisplayed"]
		inTime = permissionsAdminControls["inTime"]
		outTime = permissionsAdminControls["outTime"]
		studentDetails=[]
		permission=[]

		if request.method == 'GET':
			return render_template('/guard/permissions.html', appActivation = permissionsAppActivated, inTime = inTime, outTime = outTime, studentDetails = studentDetails, permission = permission)


		if request.method == 'POST':
			# fetch permission and student details from roll number
			if request.form['submit'].split(':')[0]=='search':
				rollNumber = request.form["student-roll-number"]
				searchParams = {'rollNumber':rollNumber}
				searchHeaders = {'Authorization': configData["AuthorizationToken"]}

				getStudentDetailsUrl = BASE_URL+"getStudentDetails"

				studentDetailsResponse = requests.request("GET", getStudentDetailsUrl, headers=searchHeaders, params=searchParams)
				studentDetails = mapStudentDetailsToList(studentDetailsResponse.json())
				
				getPermissionUrl = BASE_URL+"getPermission"
				permissionResponse = requests.request("GET", getPermissionUrl, headers=searchHeaders, params=searchParams)
				permission = mapPermissionToList(permissionResponse.json())

				return render_template('/guard/permissions.html', appActivation = permissionsAppActivated, inTime = inTime, outTime = outTime, studentDetails = studentDetails, permission = permission)
			
			elif request.form['submit'].split(':')[0]=='markExit':
				permissionId = request.form['submit'].split(':')[1]
				guardId = user[0][0]
				url = BASE_URL+"markExit"
				payload={"permissionId":permissionId, "guardId":guardId}
				headers = {'Authorization': configData["AuthorizationToken"]}
				response = requests.request("POST", url, headers=headers, data=payload)
				return redirect(url_for("guard.permissions"))


			elif request.form['submit'].split(':')[0]=='markEntry':
				permissionId = request.form['submit'].split(':')[1]
				guardId = user[0][0]
				url = BASE_URL+"markEntry"
				payload={"permissionId":permissionId, "guardId":guardId}
				headers = {'Authorization': configData["AuthorizationToken"]}
				response = requests.request("POST", url, headers=headers, data=payload)
				return redirect(url_for("guard.permissions"))

	else:
		return redirect(url_for('guard.home'))

@guard.route('/forgot-password', methods=['GET','POST'])
def forgotPassword():
	pass

@guard.route('/logout')
def logout():
    user = getCurrentGuardUser()
    if user:
        session.pop('guardID', None)
        return redirect(url_for('guard.home'))
    else:
        return redirect(url_for('guard.home'))

app/templates/guard/login.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8" />
  <link rel="apple-touch-icon" sizes="76x76" href="{{url_for('static', filename='img/apple-icon.png')}}">
  <link rel="icon" type="image/png" href="{{url_for('static', filename='img/favicon.png')}}">
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
  <title>
    Login-Page
  </title>
  <meta content='width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0, shrink-to-fit=no' name='viewport' />
  <!--     Fonts and icons     -->
  <link href="https://fonts.googleapis.com/css?family=Montserrat:400,700,200" rel="stylesheet" />
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.1/css/all.css" integrity="sha384-fnmOCqbTlWIlj8LyTjo7mOUStjsKC4pOpQbqyi7RrhN7udi9RwhKkMHpvLbHG9Sr" crossorigin="anonymous">
  <!-- CSS Files -->
  <link href="{{url_for('static', filename='css/bootstrap.min.css')}}" rel="stylesheet" />
  <link href="{{url_for('static', filename='css/now-ui-kit.css')}}" rel="stylesheet" />
  <!-- CSS Just for demo purpose, don't include it in your project -->
  <link href="{{url_for('static', filename='demo/demo.css')}}" rel="stylesheet" />
</head>

<body class="login-page sidebar-collapse">
  <!-- Navbar -->
  <nav class="navbar navbar-expand-lg bg-primary fixed-top navbar-transparent " color-on-scroll="400">
    <div class="container">
      <div class="dropdown button-dropdown">
        <a href="#pablo" class="dropdown-toggle" id="navbarDropdown" data-toggle="dropdown">
          <span class="button-bar"></span>
          <span class="button-bar"></span>
          <span class="button-bar"></span>
        </a>
       
      </div>
      <div class="navbar-translate">
        <a class="navbar-brand" href="#"rel="tooltip"  data-placement="bottom" >
          Hostel Webkiosk (Guard Login)
        </a>
        <button class="navbar-toggler navbar-toggler" type="button" data-toggle="collapse" data-target="#navigation" aria-controls="navigation-index" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-bar top-bar"></span>
          <span class="navbar-toggler-bar middle-bar"></span>
          <span class="navbar-toggler-bar bottom-bar"></span>
        </button>
      </div>
      <div class="collapse navbar-collapse justify-content-end" id="navigation" data-nav-image="../img/blurred-image-1.jpg">
      
        
        </ul>
      </div>
    </div>
  </nav>
  <!-- End Navbar -->
  <div class="page-header clear-filter" filter-color="orange">
    <div class="page-header-image" style="background-image:url('../img/login.jpeg')"></div>
    <div class="content">
      <div class="container">
        <div class="col-md-4 ml-auto mr-auto">
          {% if loginFlag == 0 %}
          <div class="alert alert-danger" role="alert">
            The username or password is incorrect!
          </div>
          {% endif %}
          <div class="card card-login card-plain">
            <form class="form" method="POST" action="{{url_for('guard.home')}}">
              <div class="card-header text-center">
                <div class="logo-container">
                  <img src="img/now-logo.png" alt="">
                </div>
              </div>
              <div class="card-body">
                <div class="input-group no-border input-lg">
                  <div class="input-group-prepend">
                    <span class="input-group-text">
                      <i class="now-ui-icons users_circle-08"></i>
                    </span>
                  </div>
                  <input name="guard-login-userID" type="text" class="form-control" placeholder="Roll Number">
                </div>
                <div class="input-group no-border input-lg">
                  <div class="input-group-prepend">
                    <span class="input-group-text">
                      <i class="fas fa-key"></i>
                    </span>
                  </div>
                  <input name="guard-login-password" type="password" placeholder="Password" class="form-control" />
                </div>
              </div>
              <div class="card-footer text-center">
                <input type="submit" class="btn btn-primary btn-round btn-lg btn-block" value="Login">
                <div class="pull-right">
                  <h6>
                    <a href="{{url_for('guard.forgotPassword')}}" class="link">Forgot Password?</a>
                  </h6>
                </div>
            </form>
            
            </div>
            
          </div>
        </div>
      </div>
    </div>
   
  </div>
  <!--   Core JS Files   -->
  <script src="{{url_for('static', filename='dashboard/js/core/jquery.min.js')}}"></script>
  <script src="{{url_for('static', filename='dashboard/js/core/popper.min.js')}}"></script>
  <script src="{{url_for('static', filename='dashboard/js/core/bootstrap.min.js')}}"></script>
  <script src="{{url_for('static', filename='dashboard/js/plugins/perfect-scrollbar.jquery.min.js')}}"></script>
  <!--  Google Maps Plugin    -->
  <script src="https://maps.googleapis.com/maps/api/js?key=YOUR_KEY_HERE"></script>
  <!-- Chart JS -->
  <script src="{{url_for('static', filename='dashboard/js/plugins/chartjs.min.js')}}"></script>
  <!--  Notifications Plugin    -->
  <script src="{{url_for('static', filename='dashboard/js/plugins/bootstrap-notify.js')}}"></script>
  <!-- Control Center for Now Ui Dashboard: parallax effects, scripts for the example pages etc -->
  <script src="{{url_for('static', filename='dashboard/js/now-ui-dashboard.min.js')}}" type="text/javascript"></script><!-- Now Ui Dashboard DEMO methods, don't include it in your project! -->
  <script src="{{url_for('static', filename='dashboard/demo/demo.js')}}"></script>
</body>

</html>