app/views/cms.py
from app import *
from app.helperFunctions import *
from flask import (Blueprint, Flask, flash, g, redirect, render_template,
                   request, send_file, session, url_for)
from flask_mysqldb import MySQL
import hashlib
from werkzeug.utils import secure_filename
from datetime import datetime
import re
import csv
from datetime import date
import pytz 
IST = pytz.timezone('Asia/Kolkata')

configData = getConfigsFromJson()
cms = Blueprint('cms', __name__, url_prefix='/cms') 
BASE_URL = configData["BASE_URL"]

# Login Page
@cms.route('/', methods=['GET','POST'])
def home():
	user = getCurrentCmsUser()

	try:
		if user:
			return redirect(url_for('cms.dashboard'))
		if request.method == 'POST':
			employeeID = request.form['cms-login-employeeID']
			password = hashlib.md5(request.form['cms-login-password'].encode())
			result=None
			result = query_db("select * from login_cms where employeeID=%s;",(employeeID,))
			if result:
				if result[0][1]==password.hexdigest():
					session['employeeID']=employeeID
					session['whatIsMyRole']=configData["cmsRole"] 
					return redirect(url_for('cms.dashboard'))
				else:
					return render_template('cms/login.html',loginFlag=0)
			else:
				return render_template('cms/login.html',loginFlag=0)
		else:
			return render_template('cms/login.html',loginFlag=1)
	except Exception as e:
		return redirect(url_for('cms.home'))

# User Profile
@cms.route('/user-profile', methods=['GET', 'POST'])
def userProfile():
	user=getCurrentCmsUser()
	cur = mysql.connection.cursor()
	if user:
		userDetails=query_db("select * from cms_employee_details where employeeID=%s;",(user[0][0],))
			
		if request.method=='GET':
			return render_template('cms/userProfile.html',employeeID = user[0][0],user=userDetails,passwordCheck=0,success=0)
		if request.method=='POST':
			if request.form['submit']=='Change Password':
				oldPassword = hashlib.md5(request.form['employee-old-password'].encode())
				newPassword = hashlib.md5(request.form['employee-new-password'].encode())
				result = query_db("select * from login_cms where employeeID=%s;",(user[0][0],))
				if result[0][1]==oldPassword.hexdigest():
					cur.execute("update login_cms set password=%s where employeeID=%s;", (newPassword.hexdigest(),user[0][0],))
					mysql.connection.commit()
					return render_template('cms/userProfile.html',employeeID = user[0][0],user=userDetails,passwordCheck=0,success=1)
				else:
					return render_template('cms/userProfile.html',employeeID = user[0][0],user=userDetails,passwordCheck=1,success=0)
			
	else:
		return redirect(url_for('cms.home'))
	cur.close()

@cms.route('/dashboard', methods=['GET','POST'])
def dashboard():
	user=getCurrentCmsUser()
	cur=mysql.connection.cursor()
	if user:
		if request.method == 'GET':
			employee_details=query_db("select * from cms_employee_details where employeeID=%s;",(user[0][0],))
			showPendingComplaints = query_db("select * from cms where deleted<>1 and status=3 and inHouse=0 order by complaintID desc;")
			showActiveComplaints = query_db("select * from cms where deleted<>1 and status in (4) and inHouse=0 order by complaintID desc;")
			showCompletedComplaints = query_db("select * from cms where deleted<>1 and status in (5,6,7,8,9) and inHouse=0 order by complaintID desc limit 20;")
			workers = query_db("select * from cms_workers_details;")
			if workers is None:
				workers=[]
			completedComplaints=[]	
			activeComplaints=[]	
			pendingComplaints=[]
			if showPendingComplaints is None:
				showPendingComplaints=[]
			for i in range(len(showPendingComplaints)):
				complaintID=showPendingComplaints[i][0]
				hostelRoomID=showPendingComplaints[i][2]
				roomNumber="Hostel Complaint"
				if hostelRoomID!=1:
					roomNumber=query_db("select roomNumber from hostel_details where hostelRoomID=%s;",(hostelRoomID,))[0][0]
				userDetails = ["name", "userID/rollnumber"]
				if showPendingComplaints[i][8]==2:
					employeeID=showPendingComplaints[i][1]
					employeeMap=query_db("select role,userID from hostel_employee_mapping where employeeID=%s;",(employeeID,))
					role = employeeMap[0][0]
					userID = employeeMap[0][1]
					userDetails[1]=employeeID
					if role == 0:
						wardenDetails=query_db("select firstName, lastName from warden_details where userID=%s;",(userID,))
						userDetails[0]=wardenDetails[0][0]+" "+wardenDetails[0][1]
					elif role == 1:
						caretakerDetails=query_db("select firstName, lastName from caretaker_details where userID=%s;",(userID,))
						userDetails[0]=caretakerDetails[0][0]+" "+caretakerDetails[0][1]
					elif role == 2:
						nCaretakerDetails=query_db("select firstName, lastName from night_caretaker_details where userID=%s;",(userID,))
						userDetails[0]=nCaretakerDetails[0][0]+" "+nCaretakerDetails[0][1]
				elif showPendingComplaints[i][8]==0:
					userID = showPendingComplaints[i][1]
					studentDeets = query_db("select rollNumber,firstName,lastName from student_details where userID=%s;",(userID,))
					userDetails[1]=studentDeets[0][0]
					userDetails[0]=studentDeets[0][1]+" "+studentDeets[0][2]
				hostelID=showPendingComplaints[i][9]
				hostelName=query_db("select hostelName from hostel_data where hostelID=%s;",(hostelID,))[0][0]
				type=showPendingComplaints[i][3]
				subject=showPendingComplaints[i][4]
				description=showPendingComplaints[i][5]
				time = showPendingComplaints[i][6]
				date = showPendingComplaints[i][13]
				status = showPendingComplaints[i][7]
				image = showPendingComplaints[i][11]
				severity = showPendingComplaints[i][16]
				if image is None:
					image = "1"
				workerID = showPendingComplaints[i][14]
				workerDeets=[]
				if workerID!=0:
					workerDeets = query_db("select name,phone from cms_workers_details where workerID=%s;",(workerID,))
				else:
					workerID="Not Alloted"
					workerDeets=[["Not Alloted","Not Alloted"]]
				workerName = workerDeets[0][0]
				workerNumber = workerDeets[0][1]
				complaint=[complaintID,userDetails[0],userDetails[1],roomNumber,hostelName,type,subject,description,time,date,status,workerName,workerNumber,image,severity]
				pendingComplaints.append(complaint)

			
			if showActiveComplaints is None:
				showActiveComplaints =[]
			for i in range(len(showActiveComplaints)):
				complaintID=showActiveComplaints[i][0]
				hostelRoomID=showActiveComplaints[i][2]
				roomNumber="Hostel Complaint"
				if hostelRoomID!=1:
					roomNumber=query_db("select roomNumber from hostel_details where hostelRoomID=%s;",(hostelRoomID,))[0][0]
				userDetails = ["name", "userID/rollnumber"]
				if showActiveComplaints[i][8]==2:
					employeeID=showActiveComplaints[i][1]
					employeeMap=query_db("select role,userID from hostel_employee_mapping where employeeID=%s;",(employeeID,))
					role = employeeMap[0][0]
					userID = employeeMap[0][1]
					userDetails[1]=employeeID
					if role == 0:
						wardenDetails=query_db("select firstName, lastName from warden_details where userID=%s;",(userID,))
						userDetails[0]=wardenDetails[0][0]+" "+wardenDetails[0][1]
					elif role == 1:
						caretakerDetails=query_db("select firstName, lastName from caretaker_details where userID=%s;",(userID,))
						userDetails[0]=caretakerDetails[0][0]+" "+caretakerDetails[0][1]
					elif role == 2:
						nCaretakerDetails=query_db("select firstName, lastName from night_caretaker_details where userID=%s;",(userID,))
						userDetails[0]=nCaretakerDetails[0][0]+" "+nCaretakerDetails[0][1]
				elif showActiveComplaints[i][8]==0:
					userID = showActiveComplaints[i][1]
					studentDeets = query_db("select rollNumber,firstName,lastName from student_details where userID=%s;",(userID,))
					userDetails[1]=studentDeets[0][0]
					userDetails[0]=studentDeets[0][1]+" "+studentDeets[0][2]
				hostelID=showActiveComplaints[i][9]
				hostelName=query_db("select hostelName from hostel_data where hostelID=%s;",(hostelID,))[0][0]
				type=showActiveComplaints[i][3]
				subject=showActiveComplaints[i][4]
				description=showActiveComplaints[i][5]
				time = showActiveComplaints[i][6]
				date = showActiveComplaints[i][13]
				status = showActiveComplaints[i][7]
				image = showActiveComplaints[i][11]
				severity = showActiveComplaints[i][16]
				if image is None:
					image = "1"
				workerID = showActiveComplaints[i][14]
				workerDeets=[]
				if workerID!=0:
					workerDeets = query_db("select name,phone from cms_workers_details where workerID=%s;",(workerID,))
				else:
					workerID="Not Alloted"
					workerDeets=[["Not Alloted","Not Alloted"]]
				workerName = workerDeets[0][0]
				workerNumber = workerDeets[0][1]
				complaint=[complaintID,userDetails[0],userDetails[1],roomNumber,hostelName,type,subject,description,time,date,status,workerName,workerNumber,image,severity]
				activeComplaints.append(complaint)
			
			if showCompletedComplaints is None:
				showCompletedComplaints =[]
			for i in range(len(showCompletedComplaints)):
				complaintID=showCompletedComplaints[i][0]
				hostelRoomID=showCompletedComplaints[i][2]
				roomNumber="Hostel Complaint"
				if hostelRoomID!=1:
					roomNumber=query_db("select roomNumber from hostel_details where hostelRoomID=%s;",(hostelRoomID,))[0][0]
				userDetails = ["name", "userID/rollnumber"]
				if showCompletedComplaints[i][8]==2:
					employeeID=showCompletedComplaints[i][1]
					employeeMap=query_db("select role,userID from hostel_employee_mapping where employeeID=%s;",(employeeID,))
					role = employeeMap[0][0]
					userID = employeeMap[0][1]
					userDetails[1]=employeeID
					if role == 0:
						wardenDetails=query_db("select firstName, lastName from warden_details where userID=%s;",(userID,))
						userDetails[0]=wardenDetails[0][0]+" "+wardenDetails[0][1]
					elif role == 1:
						caretakerDetails=query_db("select firstName, lastName from caretaker_details where userID=%s;",(userID,))
						userDetails[0]=caretakerDetails[0][0]+" "+caretakerDetails[0][1]
					elif role == 2:

app/views/guard.py
from os import stat
from werkzeug import utils
from app import *
from app.helperFunctions import *
from flask import (Blueprint, Flask, flash, g, redirect, render_template,
                   request, send_file, session, url_for)
from flask_mysqldb import MySQL
import hashlib
from werkzeug.utils import secure_filename
from datetime import datetime
from flask_mail import Mail, Message  
from datetime import date
import pandas as pd
import json
import pytz 
IST = pytz.timezone('Asia/Kolkata')

configData = getConfigsFromJson()
guard = Blueprint('guard', __name__, url_prefix='/guard') 
BASE_URL = configData["BASE_URL"]

#Login page
@guard.route('/', methods=['GET','POST'])
def home():
	user = getCurrentGuardUser()
	if user:
		return redirect(url_for('guard.permissions'))
	if request.method == 'POST':
		guardID = request.form['guard-login-userID']
		password = hashlib.md5(request.form['guard-login-password'].encode())
		result = query_db("select * from login_guard where userID=%s;",(guardID,))
		if result is not None:
			if result[0][1]==password.hexdigest():
				session['guardID']=guardID
				return redirect(url_for('guard.permissions'))
			else:
				return render_template('guard/login.html',loginFlag=0)
		else:
			return render_template('guard/login.html',loginFlag=0)
	else:
		return render_template('guard/login.html',loginFlag=1)


#permissions
@guard.route('/permissions', methods=['GET','POST'])
def permissions():
	user = getCurrentGuardUser()
	cur = mysql.connection.cursor()

	if user:

		#permissionsAdminControl
		permissionsAdminControlUrl = BASE_URL+"getPermissionsAdminControlls"
		permissionsAdminControlHeaders = {'Authorization': configData["AuthorizationToken"]}
		permissionsAdminControlResponse = requests.request("GET", permissionsAdminControlUrl, headers=permissionsAdminControlHeaders)
		permissionsAdminControls = json.loads(permissionsAdminControlResponse.text)
		permissionsAppActivated = permissionsAdminControls["activatePermissionsApp"]
		rulesInformation = permissionsAdminControls["informationToBeDisplayed"]
		inTime = permissionsAdminControls["inTime"]
		outTime = permissionsAdminControls["outTime"]
		studentDetails=[]
		permission=[]

		if request.method == 'GET':
			return render_template('/guard/permissions.html', appActivation = permissionsAppActivated, inTime = inTime, outTime = outTime, studentDetails = studentDetails, permission = permission)


		if request.method == 'POST':
			# fetch permission and student details from roll number
			if request.form['submit'].split(':')[0]=='search':
				rollNumber = request.form["student-roll-number"]
				searchParams = {'rollNumber':rollNumber}
				searchHeaders = {'Authorization': configData["AuthorizationToken"]}

				getStudentDetailsUrl = BASE_URL+"getStudentDetails"

				studentDetailsResponse = requests.request("GET", getStudentDetailsUrl, headers=searchHeaders, params=searchParams)
				studentDetails = mapStudentDetailsToList(studentDetailsResponse.json())
				
				getPermissionUrl = BASE_URL+"getPermission"
				permissionResponse = requests.request("GET", getPermissionUrl, headers=searchHeaders, params=searchParams)
				permission = mapPermissionToList(permissionResponse.json())

				return render_template('/guard/permissions.html', appActivation = permissionsAppActivated, inTime = inTime, outTime = outTime, studentDetails = studentDetails, permission = permission)
			
			elif request.form['submit'].split(':')[0]=='markExit':
				permissionId = request.form['submit'].split(':')[1]
				guardId = user[0][0]
				url = BASE_URL+"markExit"
				payload={"permissionId":permissionId, "guardId":guardId}
				headers = {'Authorization': configData["AuthorizationToken"]}
				response = requests.request("POST", url, headers=headers, data=payload)
				return redirect(url_for("guard.permissions"))


			elif request.form['submit'].split(':')[0]=='markEntry':
				permissionId = request.form['submit'].split(':')[1]
				guardId = user[0][0]
				url = BASE_URL+"markEntry"
				payload={"permissionId":permissionId, "guardId":guardId}
				headers = {'Authorization': configData["AuthorizationToken"]}
				response = requests.request("POST", url, headers=headers, data=payload)
				return redirect(url_for("guard.permissions"))

	else:
		return redirect(url_for('guard.home'))

@guard.route('/forgot-password', methods=['GET','POST'])
def forgotPassword():
	pass

@guard.route('/logout')
def logout():
    user = getCurrentGuardUser()
    if user:
        session.pop('guardID', None)
        return redirect(url_for('guard.home'))
    else:
        return redirect(url_for('guard.home'))

app/templates/cms/generateReport.html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8" />
  <link rel="apple-touch-icon" sizes="76x76" href="{{url_for('static', filename='dashboard/img/apple-icon.png')}}">
  <link rel="icon" type="image/png" href="{{url_for('static', filename='dashboard/img/favicon.png')}}">
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
  <title>
    Dashboard
  </title>
  <meta content='width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0, shrink-to-fit=no'
    name='viewport' />
  <!--     Fonts and icons     -->
  <link href="https://fonts.googleapis.com/css?family=Montserrat:400,700,200" rel="stylesheet" />
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.1/css/all.css"
    integrity="sha384-fnmOCqbTlWIlj8LyTjo7mOUStjsKC4pOpQbqyi7RrhN7udi9RwhKkMHpvLbHG9Sr" crossorigin="anonymous">
  <!-- CSS Files -->
  <link href="{{url_for('static', filename='dashboard/css/bootstrap.min.css')}}" rel="stylesheet" />
  <link href="{{url_for('static', filename='dashboard/css/now-ui-dashboard.css')}}" rel="stylesheet" />
  <!-- CSS Just for demo purpose, don't include it in your project -->
  <link href="{{url_for('static', filename='dashboard/demo/demo.css')}}" rel="stylesheet" />
  <style>
    .overlayx {
      position: absolute;
      bottom: 0;
      background: rgb(0, 0, 0);
      background: rgba(0, 0, 0, 0.603);
      /* Black see-through */
      color: #f1f1f1;
      width: 100%;
      transition: .5s ease;
      opacity: 1;
      color: white;
      font-size: 20px;
      padding: 20px;
      text-align: center;
    }
  </style>
</head>

<body class="">
  <div class="wrapper ">
    <div class="sidebar" data-color="red">
      <!--
        Tip 1: You can change the color of the sidebar using: data-color="blue | green | orange | red | yellow"
    -->
      <div class="logo">
        <a href="" class="simple-text text-center">
          Thapar University
        </a>
      </div>
      <div class="sidebar-wrapper" id="sidebar-wrapper">
        <ul class="nav">
          <li class="">
            <a href="{{url_for('cms.userProfile')}}">
              <i class="now-ui-icons users_single-02"></i>
              <p>User Profile</p>
            </a>
          </li>
          <li class="">
            <a href="{{url_for('cms.dashboard')}}">
              <i class="now-ui-icons design_app"></i>
              <p>Dashboard</p>
            </a>
          </li>
           <li class="">
            <a href="{{url_for('cms.workers')}}">
              <i class="now-ui-icons design_app"></i>
              <p>Worker Info</p>
            </a>
          </li>
          <li class="active">
            <a href="{{url_for('cms.generateReport')}}">
              <i class="fas fa-scroll"></i>
              <p>Reports</p>
            </a>
          </li>
        </ul>
      </div>
    </div>
    <div class="main-panel" id="main-panel">
      <!-- Navbar -->
      <nav class="navbar navbar-expand-lg navbar-transparent  bg-primary  navbar-absolute">
        <div class="container-fluid">
          <div class="navbar-wrapper">
            <div class="navbar-toggle">
              <button type="button" class="navbar-toggler">
                <span class="navbar-toggler-bar bar1"></span>
                <span class="navbar-toggler-bar bar2"></span>
                <span class="navbar-toggler-bar bar3"></span>
              </button>
            </div>
            <a class="navbar-brand" href="#">Hello <b>{{user[0][1]}}!</b></a>
          </div>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navigation" aria-controls="navigation-index" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-bar navbar-kebab"></span>
            <span class="navbar-toggler-bar navbar-kebab"></span>
            <span class="navbar-toggler-bar navbar-kebab"></span>
          </button>
          <div class="collapse navbar-collapse justify-content-end" id="navigation">
           
            <ul class="navbar-nav">
              <!-- <li class="nav-item">
                <a class="nav-link" href="#pablo">
                  <i class="now-ui-icons media-2_sound-wave"></i>
                  <p>
                    <span class="d-lg-none d-md-block">Stats</span>
                  </p>
                </a>
              </li> -->
              <!-- <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  <i class="now-ui-icons location_world"></i>
                  <p>
                    <span class="d-lg-none d-md-block">Some Actions</span>
                  </p>
                </a>
                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdownMenuLink">
                  <a class="dropdown-item" href="#">Action</a>
                  <a class="dropdown-item" href="#">Another action</a>
                  <a class="dropdown-item" href="#">Something else here</a>
                </div>
              </li> -->
              <li class="nav-item">
                <a class="navbar-brand" href="{{url_for('cms.logout')}}">
                  <i class="fas fa-sign-out-alt"></i>
                  <p>
                    &nbsp;logout
                  </p>
                </a>
              </li>
            </ul>
          </div>
        </div>
      </nav>
      <!-- End Navbar -->
      <div class="panel-header panel-header-lg">
        <h2 align="center" class="d-sm-block" style="color:white; margin-left: 2rem;">WELCOME TO HOSTEL COMPLAINT MANAGEMENT SYSTEM</h2>
        <div class="container">
          

        </div>

      </div>
      <div class="content" style="margin-top: -90px;">
        <div class="row">
          <div class="col-md-12">
            <div class="card">
              <div class="card-header">
                <h5 class="title">Generate Hostel Complaints Report</h5>
              </div>
              <div class="card-body">
                <form method="POST" action="{{url_for('cms.generateReport')}}">
                  <div class="row">
                    <div class="col-md-4 pr-1">
                      <div class="form-group">
                        <label class="label-control">From Date:</label>
                        <input type="text" class="form-control datetimepicker1 mx-auto" name="startDate" placeholder="DD-MM-YYYY" required/>
                      </div>
                    </div>
                    <div class="col-md-4 pr-1">
                      <div class="form-group">
                        <label class="label-control">To Date:</label>
                        <input type="text" class="form-control datetimepicker2 mx-auto" name="endDate" placeholder="DD-MM-YYYY" required/>
                      </div>
                    </div>
                    <div class="col-md-3 pr-1">
                      <div class="form-group">
                        <label>Select Hostel</label>
                        <select class="form-select form-control" aria-label="Default select example"
                          name="select-hostel" required>
                          <option value="all" selected>All</option>
                          {%for hostel in hostelList %}
                          <option value="{{hostel[1]}}">{{hostel[1]}}</option>
                          {%endfor%}
                        </select>
                      </div>
                    </div>
                  </div>
                  <div class="row">
                    <div class="col-md-4 pr-1">
                      <div class="form-group">
                        <label>Type of Complaint</label>
                        <select class="form-select form-control" aria-label="Default select example"
                          name="type-of-complaint" required>
                          <option value="all" selected>All</option>
                          {%for complaintType in complaintTypes %}
                          <option value="{{complaintType[1]}}">{{complaintType[1]}}</option>
                          {%endfor%}
                        </select>
                      </div>
                    </div>
                    <div class="col-md-4 pr-1">
                      <div class="form-group">
                        <label>Status</label>
                        <select class="form-select form-control" aria-label="Default select example"
                          name="status" required>
                          <option value="all" selected>All</option>
                          <option value="Active">Active</option>
                          <option value="Pending allotment to worker">Pending allotment to worker</option>
                          <option value="Completed">Completed</option>
                        </select>
                      </div>
                    </div>
                    <div class="col-md-3 pr-1" style="padding-top: 0.75rem;">
                      <div class="form-group">
                        <button type="submit" class="btn btn-primary btn-round btn-small btn-block" name="submit" value="GenerateReport"> Generate Report</button>
                      </div>
                    </div>
                  </div>
                </form>
              </div>
            </div>
          </div>
        </div>
      </div>
      </div>
    </div>
  </div>
  <!--   Core JS Files   -->
  <script src="{{url_for('static', filename='dashboard/js/core/jquery.min.js')}}"></script>
  <script src="{{url_for('static', filename='dashboard/js/core/popper.min.js')}}"></script>
  <script src="{{url_for('static', filename='dashboard/js/core/bootstrap.min.js')}}"></script>
  <script src="{{url_for('static', filename='dashboard/js/plugins/perfect-scrollbar.jquery.min.js')}}"></script>
  <!--  Google Maps Plugin    -->
  <script src="https://maps.googleapis.com/maps/api/js?key=YOUR_KEY_HERE"></script>
  <!-- Chart JS -->
  <script src="{{url_for('static', filename='dashboard/js/plugins/moment.min.js')}}" type="text/javascript"></script>
  <script src="{{url_for('static', filename='dashboard/js/plugins/chartjs.min.js')}}"></script>
  <script src="{{url_for('static', filename='dashboard/js/plugins/bootstrap-datetimepicker.min.js')}}" type="text/javascript"></script>
  <script src="{{url_for('static', filename='dashboard/js/plugins/bootstrap-datepicker.js')}}"></script>
  <!--  Notifications Plugin    -->
  <script src="{{url_for('static', filename='dashboard/js/plugins/bootstrap-notify.js')}}"></script>
  <!-- Control Center for Now Ui Dashboard: parallax effects, scripts for the example pages etc -->
  <script src="{{url_for('static', filename='dashboard/js/now-ui-dashboard.min.js')}}" type="text/javascript"></script>
  <!-- Now Ui Dashboard DEMO methods, don't include it in your project! -->
  <script src="{{url_for('static', filename='dashboard/demo/demo.js')}}"></script>
  <script>
    $(document).ready(function () {
      // Javascript method's body can be found in static/dashboard/js/demos.js
      demo.initDashboardPageCharts();

    });

  </script>
  <script>
    $(document).ready(function () {
      $("#myInput1").on("keyup", function () {
        var value = $(this).val().toLowerCase();
        $("#myTable1 tr").filter(function () {
          $(this).toggle($(this).text().toLowerCase().indexOf(value) > -1)
        });
      });
    });
    $(document).ready(function () {
      $("#myInput2").on("keyup", function () {
        var value = $(this).val().toLowerCase();
        $("#myTable2 tr").filter(function () {
          $(this).toggle($(this).text().toLowerCase().indexOf(value) > -1)
        });
      });
    });
    $(document).ready(function () {
      $("#myInput3").on("keyup", function () {
        var value = $(this).val().toLowerCase();
        $("#myTable3 tr").filter(function () {
          $(this).toggle($(this).text().toLowerCase().indexOf(value) > -1)
        });
      });
    });
    jQuery(function ($) {
      $('body').on('click', '#selectAll', function () {
        $('.form-check-input').prop('checked', this.checked);
      });

      $('body').on('click', '.form-check-input', function () {
        if ($('.form-check-input').length == $('.form-check-input:checked').length) {
          $('#selectAll').prop('checked', true);
        } else {
          $("#selectAll").prop('checked', false);
        }

      });
    });
  </script>
  <script>
    $('.datetimepicker1').datetimepicker({
      icons: {
          time: "fa fa-clock-o",
          date: "fa fa-calendar",
          up: "fa fa-chevron-up",
          down: "fa fa-chevron-down",
          previous: 'fa fa-chevron-left',
          next: 'fa fa-chevron-right',
          today: 'fa fa-screenshot',
          clear: 'fa fa-trash',
          close: 'fa fa-remove'
      },
      format: 'DD-MM-YYYY',
  });
  $('.datetimepicker2').datetimepicker({
      icons: {
          time: "fa fa-clock-o",
          date: "fa fa-calendar",
          up: "fa fa-chevron-up",
          down: "fa fa-chevron-down",
          previous: 'fa fa-chevron-left',
          next: 'fa fa-chevron-right',
          today: 'fa fa-screenshot',
          clear: 'fa fa-trash',
          close: 'fa fa-remove'
      },
      format: 'DD-MM-YYYY',
  });
</script>
</body>

</html>